[package]
name = "admin/project-w"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
bytenet-max = "elitriare/bytenet-max@0.2.7"
promise = "evaera/promise@4.0.0"