-- File: ReplicatedStorage/Shared/Components/ColorTemplate.luau
local ColorTemplate = {
    MainButtons = {
        Inventory = Color3.fromRGB(255, 237, 166),
        Profession = Color3.fromRGB(157, 255, 209),
        Upgrade = Color3.fromRGB(255, 167, 255),
        Crafting = Color3.fromRGB(255, 216, 196),
        Classes = Color3.fromRGB(158, 247, 255),
        Party = Color3.fromRGB(99, 182, 255),
        Settings = Color3.fromRGB(148, 255, 148),
        Exit = Color3.fromRGB(255, 148, 148),
        Default = Color3.fromRGB(175, 175, 175),
    },

}

return ColorTemplate